### ISSUE TITLE
Sync with AdGuard Home for Homeassistant Addon

### ISSUE THREAD

**Issue by rpruden** [bakito/adguardhome-sync#633]
### What happened?

I am unable to sync with my adguard Home for homeassistant addon. I receive teh following error,

2025-08-30T13:25:09.278-0600    ERROR   client  client/client-methods.go:102    there seems to be an authentication issue - please check https://github.com/bakito/adguardhome-sync/wiki/FAQ      {"host": "ha.[domain].me:3111", "method": "GET", "path": "/profile", "status": 401}

I'm using an alternate port (3111). I believe that this is failing because the Home Assistant addon does not use Forms Based Auth. It comes up with a browser login window instead. I have also tried disabling Auth all together (leave_front_door_open) and it will not authenticate this way either. Are you able to either add an option to allow non Forms Based Auth, or allow it to access the url without providing Auth? I am really not sure why it's getting a 401 since it doesn't even promp for auth currently. I would have assumed it would silently fail open.

### AdguardHome-Sync Version

latest

### AdguardHome Version

latest

### Configuration

```shell
from unaid GUI
```

### Relevant log output

```shell
2025-08-30T13:25:09.278-0600    ERROR   client  client/client-methods.go:102    there seems to be an authentication issue - please check https://github.com/bakito/adguardhome-sync/wiki/FAQ      {"host": "ha.[domain].me:3111", "method": "GET", "path": "/profile", "status": 401}
```

**Comment by bakito** [comment]
I have the HA adguardhome running myself.
The `Web interface` port in the HA addon config is 3000.

I can connect using these settings:

```
ORIGIN_URL: https://ha.home.net:3000
ORIGIN_USERNAME: ha-user
ORIGIN_PASSWORD: ha-pass
```

**Comment by rpruden** [comment]
I changed the default port from 3000 to 3111 because there is apparently already something else using port 3000 on my HASSOS. I can connect just fine to the 3111 port manually. Since creating this, I have trie disabling SSL as well.

I actually just did some more testing, If I change the order and sync TO the HA from the ADGH server, then it works. It still throws auth errors in the log, but it works. I did enable CONTINUE_ON_ERROR=true so that may be helping. I am getting the following error when trying to sync FROM HA to ADGH.

2025-08-30T14:35:26.856-0600    INFO    sync    sync/sync.go:40 AdGuardHome sync        {"version": "v0.7.8", "build": "2025-07-16T15:08:19Z", "os": "linux", "arch": "amd64"}
2025-08-30T14:35:26.856-0600    INFO    sync    sync/sync.go:65 Setup cronjob   {"cron": "0 */2 * * *", "next-execution": "2025-08-30T16:00:00.000-0600"}
2025-08-30T14:35:26.857-0600    INFO    sync    sync/http.go:120        Starting API server     {"port": 8080}
2025-08-30T14:35:26.857-0600    INFO    sync    sync/sync.go:87 Running sync on startup
2025-08-30T14:35:41.895-0600    INFO    sync    sync/sync.go:182        Connected to origin     {"from": "ha.[domain].me:3111", "version": "v0.107.65"}
2025-08-30T14:35:41.930-0600    ERROR   client  client/client-methods.go:102    there seems to be an authentication issue - please check https://github.com/bakito/adguardhome-sync/wiki/FAQ      {"host": "ha.[domain].me:3111", "method": "GET", "path": "/profile", "username": "localuser", "status": 401}
github.com/bakito/adguardhome-sync/pkg/client.checkAuthenticationIssue
        /go/src/app/pkg/client/client-methods.go:102
github.com/bakito/adguardhome-sync/pkg/client.(*client).doGet
        /go/src/app/pkg/client/client-methods.go:35
github.com/bakito/adguardhome-sync/pkg/client.(*client).ProfileInfo
        /go/src/app/pkg/client/client.go:445
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
        /go/src/app/pkg/sync/sync.go:184
github.com/bakito/adguardhome-sync/pkg/sync.runOnStartAsync.func1
        /go/src/app/pkg/sync/sync.go:88
2025-08-30T14:35:41.930-0600    ERROR   sync    sync/sync.go:186        Error getting profileInfo info  {"from": "ha.[domain].me:3111", "error": "401 Unauthorized"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
        /go/src/app/pkg/sync/sync.go:186
github.com/bakito/adguardhome-sync/pkg/sync.runOnStartAsync.func1
        /go/src/app/pkg/sync/sync.go:88

So for some reason it seems to have troule pulling profileInfo from the ha url.

**Comment by rpruden** [comment]
ah, apparently it is the zwavejs addon that uses 3000 by default.

**Comment by rpruden** [comment]
Just to be thorough, I disabled zwavejs and reconfigured the adguard home addon to use the default port of 3000 and I still get the same issue. ( i have since reverted and went back to the alt port of 3111 just so that my zwave will keep functioning)

Right now it seems that I can set my Home Assistant as a Replica, but not an Origin. Either way, I see error messages about authentication.

2025-08-30T23:22:00.084-0600    INFO    sync    sync/sync.go:182        Connected to origin     {"from": "172.27.86.10", "version": "v0.107.65"}
2025-08-30T23:22:01.018-0600    INFO    sync    sync/sync.go:275        Start sync      {"from": "172.27.86.10", "to": "ha.prudencio.me:3111"}
2025-08-30T23:22:16.051-0600    INFO    sync    sync/sync.go:296        Connected to replica    {"from": "172.27.86.10", "to": "ha.[domain].me:3111", "version": "v0.107.65"}
2025-08-30T23:22:16.069-0600    ERROR   client  client/client-methods.go:102    there seems to be an authentication issue - please check https://github.com/bakito/adguardhome-sync/wiki/FAQ      {"host": "ha.[domain].me:3111", "method": "GET", "path": "/profile", "username": "localuser", "status": 401}
github.com/bakito/adguardhome-sync/pkg/client.checkAuthenticationIssue
        /go/src/app/pkg/client/client-methods.go:102
github.com/bakito/adguardhome-sync/pkg/client.(*client).doGet
        /go/src/app/pkg/client/client-methods.go:35
github.com/bakito/adguardhome-sync/pkg/client.(*client).ProfileInfo
        /go/src/app/pkg/client/client.go:445
github.com/bakito/adguardhome-sync/pkg/sync.init.func1
        /go/src/app/pkg/sync/action-general.go:13
github.com/bakito/adguardhome-sync/pkg/sync.(*defaultAction).sync
        /go/src/app/pkg/sync/action.go:98
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo
        /go/src/app/pkg/sync/sync.go:320
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
        /go/src/app/pkg/sync/sync.go:263
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func1
        /go/src/app/pkg/sync/sync.go:59
github.com/robfig/cron/v3.FuncJob.Run
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136
github.com/robfig/cron/v3.(*Cron).startJob.func1
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312
2025-08-30T23:22:16.069-0600    ERROR   sync    sync/sync.go:321        Error syncing profile info      {"from": "172.27.86.10", "to": "ha.[domain].me:3111", "error": "401 Unauthorized"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo
        /go/src/app/pkg/sync/sync.go:321
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
        /go/src/app/pkg/sync/sync.go:263
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func1
        /go/src/app/pkg/sync/sync.go:59
github.com/robfig/cron/v3.FuncJob.Run
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136
github.com/robfig/cron/v3.(*Cron).startJob.func1
        /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312
2025-08-30T23:22:16.120-0600    ERROR   sync    sync/sync.go:283        Sync done       {"from": "172.27.86.10", "to": "ha.[domain].me:3111", "duration": "1.46e-07s"}

I can confirm by making changes that the changes actualy DO sync. I would really much rather keep my Home Assistant addon as my Origin. Do you have any thoughts as to why this might be happening or what can be done to fix it? As mentioned in the previous post, the error received when homeassistant addon is set as the origin is a little different,

2025-08-30T14:35:41.930-0600 ERROR sync sync/sync.go:186 Error getting profileInfo info {"from": "ha.[domain].me:3111", "error": "401 Unauthorized"}

I will appreciate any guidance you may be able to provide.

**Comment by rpruden** [comment]
It may be related to this

https://github.com/AdguardTeam/AdGuardHome/issues/7985

I do get that same red error message in teh corner when logging in, though seemingly benign, perhaps that is what is causing the breakage.

**Comment by bakito** [comment]
I can confirm, the issue after upgrading to v0.107.65
I guess we have to wait for a fix and new release.

https://github.com/AdguardTeam/AdGuardHome/issues/7987

**Comment by rpruden** [comment]
Thanks for checking on your end too.

To anyone who is using the Home Assistant Addon as a replica, it still works if you add the following parameter, CONTINUE_ON_ERROR=true

Hopefully the upstream fix is pushed soon and we can use it as an origin again in the near future.

**Comment by JtwoA** [comment]
> To anyone who is using the Home Assistant Addon as a replica, it still works if you add the following parameter, CONTINUE_ON_ERROR=true

To clarify, if the HA Addon is the host, not the replica, then nada/no dice even if making this change?

**Comment by rpruden** [comment]
> > To anyone who is using the Home Assistant Addon as a replica, it still works if you add the following parameter, CONTINUE_ON_ERROR=true
> 
> To clarify, if the HA Addon is the host, not the replica, then nada/no dice even if making this change?

Affirmative. That is 100% correct. For now, I am using the HA Addon as my replica until a future version fixes the problem.

**Comment by JtwoA** [comment]
> Affirmative. That is 100% correct. For now, I am using the HA Addon as my replica until a future version fixes the problem.

To do that I'll need to do a lot of manual blocklist migration.  HA Addon is my primary (I just learned of the sync yesterday).

**Comment by bakito** [comment]
#650 implements a workaround:

If CONTINUE_ON_ERROR=true and the profile request returns 401, the process continues

**Comment by JtwoA** [comment]
> [#650](https://github.com/bakito/adguardhome-sync/pull/650) implements a workaround:
> 
> If CONTINUE_ON_ERROR=true and the profile request returns 401, the process continues

If you are using sync between two instances AND the HA Addon instance is the source, this does not work to mitigate.  To clarify, if the HA Addon is the host, not the replica, then nada/no dice even if making this change.

**Comment by bakito** [comment]
[v0.7.9](https://github.com/bakito/adguardhome-sync/releases/tag/v0.7.9) implements a workaround that ignores the 401 on the origin request, if `CONTINUE_ON_ERROR` is enabled

**Comment by bakito** [comment]
Fixed with 

[addon-adguard-home v5.3.3](https://github.com/hassio-addons/addon-adguard-home/releases/tag/v5.3.3)
[AdGuard Home v0.107.66](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.66)
